apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "paymentservice-mtls"
spec:
  host: paymentservice.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "paymentservice-mtls"
spec:
  targets:
  - name: paymentservice
  peers:
  - mtls: {}
